stages:
  - name: Build Docker Image
    when:
      branch: master
      event: [push, pull_request]
    steps:
      - runScriptConfig:
          name: "Test and audit"
          image: node:12-alpine
          shellScript: |-
            npm --version
            npm audit    
            npm install
            npm run lint
            npm run build
            npm run test
      - publishImageConfig:
          name: "Generate Docker Image "
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: pokedex/www:latest
          registry: 10.43.35.128
        env:
          PLUGIN_INSECURE: "true"
timeout: 180
notification: {}
