stages:
- name: Build Docker Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pokedex
      pushRemote: true
      registry: http://52.213.194.49:32682
  when:
    branch:
      include:
      - master
timeout: 60
notification: {}
