stages:
- name: Build Docker Image
  steps:
  - runScriptConfig:
      image: node:12-alpine
      shellScript: "npm --version\nnpm audit    \nnpm install\nnpm run lint\nnpm run
        build\nnpm run test"
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pokedex:${CICD_EXECUTION_SEQUENCE}
    env:
      PLUGIN_INSECURE: "true"
  when:
    branch:
      include:
      - master
    event:
      include:
      - push
      - pull_request
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
