stages:
- name: Build Docker Image
  steps:
  - runScriptConfig:
      image: node:12-alpine
      shellScript: |-
        npm i
        npm run lint
        npm run build
        npm run test        
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pokedex
      registry: 10.43.35.128
  when:
    branch:
      include:
      - master
timeout: 60
notification: {}
