stages:
- name: Build Docker Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pokedex/v1
      pushRemote: true
      registry: 10.43.35.128
  when:
    branch:
      include:
      - master
timeout: 60
notification: {}
