stages:
- name: Generate Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pokedex-tutorial
      pushRemote: true
      registry: 127.0.0.1:34029
timeout: 60
notification: {}
