stages:
  - name: Build Docker Image
    when:
      branch: master
      event: [push, pull_request]
    steps:
      - runScriptConfig:
          name: 'Test and audit'
          image: node:12-alpine
          shellScript: |-
            npm --version
            npm audit    
            npm install
            npm run lint
            npm run build
            npm run test
      - publishImageConfig:
          name: 'Generate Docker Image '
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: pokedex:${CICD_EXECUTION_SEQUENCE}
        env:
          PLUGIN_INSECURE: 'true'
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml
timeout: 60
notification: {}
