apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex
  labels:
    app: pokedex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokedex
  template:
    metadata:
      labels:
        app: pokedex
    spec:
      containers:
        - name: pokedex
          image: docker-registry.p-722bx-pipeline/pokedex:latest
          ports:
            - containerPort: 80
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
