kind: Service
apiVersion: v1
metadata:
  name: pokedex-service
spec:
  selector:
    app: pokedex
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex
  labels:
    app: pokedex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokedex
  template:
    metadata:
      labels:
        app: pokedex
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: pokedex
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
